
on: push

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Output versions
        run: |
          git --version
          node --version
          npm --version
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: foodgood-restaurant--front-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Tests
        run: npm test
